### PR TITLE
Implement student and subject management features

### PR DESCRIPTION
**Pull request by StephanieGacita**
This pull request implements the Student Management feature for the Student Management API. It includes the creation, retrieval, updating, and filtering of student records.

### CODE REVIEW

**Comment by 0xCyyy3000** [comment]
Hi @StephanieGacita! Kindly include your section and full name, cheers! 🥂

**Comment by StephanieGacita** [comment]
Where po sir ig bubutang?

**Comment by StephanieGacita** [comment]
Stephanie A. Gacita BSIT3B po sir

**Comment by 0xCyyy3000** [comment]
Nice try

**Pull request closed without merging**
